@JustLanguage_HostAddress = http://localhost:5098/api

POST {{JustLanguage_HostAddress}}/ParseRules
Content-Type: application/json

{
  "name": "Rule 1",
  "rule" : "test",
  "SupportDomains" : [
    {"domain" : "test1"} ,
    {"domain" : "test2"} ,
    {"domain" : "test3"}
  ]
}

###
